// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PermissionRequest.Infraestructure.Context;

namespace PermissionRequest.Infraestructure.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20220703020131_Migracion")]
    partial class Migracion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("PermissionRequest.App.PermissionRequest.Domain.Models.PermissionsModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .UseIdentityColumn();

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApellidoEmpleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ApellidoEmpleado");

                    b.Property<DateTime>("FechaPermiso")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaPermiso");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreEmpleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NombreEmpleado");

                    b.Property<int?>("TipoPermiso")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("TipoPermiso");

                    b.HasKey("Id");

                    b.ToTable("Permiso");
                });

            modelBuilder.Entity("PermissionRequest.App.PermissionRequest.Domain.Models.PermissionsTypeModel", b =>
                {
                    b.Property<int?>("Id")
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Descripcion");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TipoPermiso");
                });

            modelBuilder.Entity("PermissionRequest.App.PermissionRequest.Domain.Models.PermissionsTypeModel", b =>
                {
                    b.HasOne("PermissionRequest.App.PermissionRequest.Domain.Models.PermissionsModel", "Permissions")
                        .WithOne("PermissionsType")
                        .HasForeignKey("PermissionRequest.App.PermissionRequest.Domain.Models.PermissionsTypeModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("PermissionRequest.App.PermissionRequest.Domain.Models.PermissionsModel", b =>
                {
                    b.Navigation("PermissionsType");
                });
#pragma warning restore 612, 618
        }
    }
}
